apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
  labels:
    app: app
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "latest"
automountServiceAccountToken: false