apiVersion: v1
kind: ServiceAccount
metadata:
  name: wso2-sa
  namespace: wso2
  labels:
    app: wso2-identity-server
    app.kubernetes.io/name: wso2-identity-server
    app.kubernetes.io/instance: wso2-identity-server
    app.kubernetes.io/version: "latest"
automountServiceAccountToken: false